import { useEffect } from "react";
import { useDispatch} from "react-redux";
import Head from 'next/head';
import axios from 'axios';

import {withLayout} from "../layout/Layout";
import {getMovieByName, getMovie} from '../config';
import {writeMoviesFiltered} from '../store/movies/actions-movies';

import Hero from '../components/Hero';
import Filter from '../components/Filter';
import MoreMovies from '../components/MoreMovie';
import Subscribe from '../components/Form';

const Home = ({HeroSsrFetch, MoviesSsrFetch}) => {
	const dispatch = useDispatch();

	useEffect(() => {
		dispatch(writeMoviesFiltered(MoviesSsrFetch));
		// eslint-disable-next-line
	}, [MoviesSsrFetch]);

	return (
		<>
			<Head>
				<title>MovieVerse</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				
			</Head>
			<Hero hero={HeroSsrFetch}/>
			<Filter/>
			<MoreMovies/>
			<Subscribe/>
		</>
	)
};


export const getServerSideProps = async () => {
	const {data: hero} = await axios.get(getMovieByName('Puss in Boots: The Last Wish'));
	const {data: movies} = await axios.get(getMovie(1));

	if(!hero && !movies){
		return{
			notFound: true
		}
	}

	return{
		props:{
			HeroSsrFetch: hero.results[0],
			MoviesSsrFetch: movies.results
		}
	}
}

export default withLayout(Home);
